// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-cat-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";
var list_cat_posts_default = defineTool({
  name: "list_cat_posts",
  title: "List cat blog posts",
  description: "List published blog posts from Stevie Bridget & Jewels — the two Maine Coon sisters chronicling a 50-state sunset road trip. Returns title, slug, location, post_date, and tags for each post.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("cat_posts").select("slug,title,location,post_date,tags").eq("published", true).order("post_date", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-cat-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_cat_post_default = defineTool2({
  name: "get_cat_post",
  title: "Get a cat blog post",
  description: "Fetch a single published blog post by slug, including the full markdown body written in Stevie Bridget & Jewels' voices.",
  inputSchema: {
    slug: z2.string().min(1).describe("The post slug, e.g. 'sunset-in-bar-harbor'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("cat_posts").select("slug,title,location,post_date,tags,body_md,photo_url").eq("slug", slug).eq("published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Post not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/project-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
var project_info_default = defineTool3({
  name: "project_info",
  title: "About this project",
  description: "Returns a short description of the Chasing the Sunlight project: a tribute to Steven Reed and a 50-state road trip capturing sunsets, chronicled by Maine Coon sisters Stevie Bridget & Jewels.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      name: "Chasing the Sunlight",
      tribute: "Steven Reed (9.19.66 – 5.15.25)",
      philosophy: "Never forget to look up.",
      description: "A tribute road-trip project photographing sunsets in all 50 U.S. states, narrated by Maine Coon sisters Stevie Bridget and Jewels."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jetjimvctewejkdcbncb";
var mcp_default = defineMcp({
  name: "chasing-the-sunlight-mcp",
  title: "Chasing the Sunlight",
  version: "0.1.0",
  instructions: "Tools for the Chasing the Sunlight project — a tribute road trip photographing sunsets in all 50 states, chronicled by Maine Coon sisters Stevie Bridget & Jewels. Use `list_cat_posts` to browse posts, `get_cat_post` to read one, and `project_info` for background on the project.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_cat_posts_default, get_cat_post_default, project_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
